### ISSUE TITLE
Bug Report: VS Code Cannot Register Existing Domain

### ISSUE THREAD

**Issue by m-reza-rahman** [payara/ecosystem-support#56] opened 2022-09-16 00:42 UTC
# Description #
----------
I think a bug was introduced in the VS Code plugin or something is broken in the latest VS Code and Payara. I am unable to register an existing Payara 5 domain (domain1). This used to work fine.

## Environment ##
Windows - 11 22H2
Java - 17.0.3.1 2022-04-22 LTS
VS Code - 1.71.2
Payara Tools - v1.1.1
Payara - 5.2022.2

**Comment by JamesHillyard** [comment] 2022-09-20 14:14
Hi @m-reza-rahman,

I was able to add a local domain to the latest version of VS Code and Payara Tools successfully. Could you please share more details about what happens when you try to register an existing domain?

Thanks,
James

**Comment by NailykSturm** [comment] 2022-09-27 08:17
Hello @JamesHillyard,

Like @m-reza-rahman, I can't select a domain when I'm trying to add a server

For the environement, I use
- Linux Garuda (from Arch Linux) 
- Java 17.0.3.1 2022-04-22 LTS
- VsCode 1.71.2
- Payara 5.2022.3

**Comment by JamesHillyard** [comment] 2022-09-27 08:22
Hi @NailykSturm,

Could you please attach a screenshot in place of where the `select domain` option used to be and what is now occurring for you? I still haven't been able to reproduce this locally on the following environment: 

- Windows 10 Pro
- Zulu JDK 17.0.2
- VS Code 1.71.2
- Payara 5.2022.3

Thanks,
James

**Comment by NailykSturm** [comment] 2022-09-27 08:30
I don't know if this what you expected, but, when I'm select a domain, there is nothing happening
 
![Screenshot_bug_selecting_domain_vscode](https://user-images.githubusercontent.com/47662089/192474564-32910d09-113d-4c2a-a1c3-3c0cd9f1e741.png)

**Comment by JamesHillyard** [comment] 2022-09-27 08:32
Thank you for sharing a screenshot, that's not what I was expecting. That is the same popup I have locally, where I'm able to click one of the domains in the dropdown that I want to register to VS Code.

Are you unable to click domain1 at this point?

Thanks,
James

**Comment by NailykSturm** [comment] 2022-09-27 08:35
I can click on it, but nothing happend after. 
I've trying to click on it when the server is started and when the server is down, but nothing changes

**Comment by NailykSturm** [comment] 2022-09-27 08:45
I think, I worked around the problem, because instead of selecting a local domain, I've selected one remonte and for now, it work

Thanks for the help ^^

**Comment by m-reza-rahman** [comment] 2022-09-27 18:40
I can confirm my issue is the same as @NailykSturm. How can we help debug this issue? Does scheduling a debugging session make sense or recording a video?

**Comment by JamesHillyard** [comment] 2022-09-28 07:59
Hi @m-reza-rahman,

A short recording of the issue would help showcase the exact error you are encountering. I have managed to inconsistently reproduce an issue which sounds similar to what @NailykSturm reported where you click the domain name and nothing happens, clicking the button repeatedly does eventually work though.

Thanks,
James

**Comment by m-reza-rahman** [comment] 2022-10-06 19:31
Here is a video the best I have time to produce: https://drive.google.com/file/d/15HWIY5PjrFmXe0ENRaVimIumJD8c7UYw/view?usp=sharing. We are all talking about the same problem and the same symptoms. I cannot get this to work at all.

**Comment by Elifzeynepedman** [comment] 2022-10-17 12:07
Hi @NailykSturm @m-reza-rahman,

I have been able to reproduce it locally. It seems wrong configurations of the environment variables might be the cause of this. 

Can you please try configuring the JAVA_HOME and java Path environment variables?
`
path = %JAVA_HOME%\bin
`
`JAVA_HOME = C:\Program Files\Java\jdk-17.0.3.1
`



Thanks,
Elif

**Comment by m-reza-rahman** [comment] 2022-10-31 19:55
I can confirm this works. Should it be documented somewhere?

**Comment by Elifzeynepedman** [comment] 2022-11-01 08:53
Hi @m-reza-rahman 

I have recently added this to the Payara VSCode extension documentation so that it is clearer in the future, however, it has not been published yet.

Thanks,
Elif

**Comment by JamesHillyard** [comment] 2022-12-12 15:31
Documentation has been merged and published. Thanks for raising this issue and your continued assistance in tracking down the cause, it's much appreciated.

**Closed as completed by JamesHillyard** 2022-12-12 15:31 UTC
Labels: Status: Pending, Type: Bug

**Comment by Chaitanya052002** [comment] 2023-12-01 04:50
Facing same issue as @NailykSturm  with local domain. Unable to click on domain1.  



C:\Users\Chaitanya>set PATH=%JAVA_HOME%\bin;%PATH%

C:\Users\Chaitanya>echo %JAVA_HOME%
C:\Program Files\Java\jdk-11

C:\Users\Chaitanya>java -version
java version "11.0.20" 2023-07-18 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.20+9-LTS-256)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.20+9-LTS-256, mixed mode)



path also looks fine still error with payara 6 on vscode.
