### ISSUE TITLE
Bug Report: Cannot authenticate at AWS via assuming IAM role

### ISSUE THREAD

**Issue by lcmgh** [payara/ecosystem-support#75] opened 2023-08-30 12:00 UTC
### Brief Summary

The Cloud Connectors do not support assuming an IAM role after authenticating via IAM User credentials.

### Expected Outcome

* Authentication via AWS credentials
* Assume Role, in the background assume role is refreshed before expiration

### Current Outcome

Not possible to assume IAM role after authenticating user

### Reproducer

-

### Operating System

n/a

### JDK Version

n/a

### Ecosystem Tool

IntelliJ IDEA IDE Plugin

**Comment by felixif** [comment] 2023-08-31 15:50
Hello @lcmgh,

What version of the cloud connector are you using? The SSO authentication works on version 2 of the connector. Is the Amazon account configured with the role that you wish, and configured following the documentation here?  https://docs.payara.fish/community/docs/Technical%20Documentation/Ecosystem/Connector%20Suites/Cloud%20Connectors/Amazon%20SQS/SSO%20Integration.html#configure-aws-iam-identity-center

If yes, and the issue is from the connector, could you please provide the steps to reproduce the issue? 

Best regards,
Felix

**Comment by felixif** [comment] 2023-09-19 14:12
Hello @lcmgh,

You have not returned within two weeks with an update, so I will close this issue for now. Please feel free to re-open the issue if you are still encountering issues with the cloud connector.

Best regards,
Felix

**Closed as completed by felixif** 2023-09-19 14:12 UTC
Labels: Status: Open, Type: Bug
