### ISSUE TITLE
Issue installing Payara tools on Eclipse (2021-09)

### ISSUE THREAD

**Issue by Marc-GHAFOUR** [payara/ecosystem-support#40] opened 2021-12-01 13:20 UTC
Hello, 
Installation of payara tools on Eclipse (2021-09) fails with the following error : 
Cannot complete the install because one or more required items could not be found.
  Software being installed: Payara Tools 1.4.0.202110041326 (org.eclipse.payara.tools.feature.group 1.4.0.202110041326)
  Missing requirement: Payara Tools 1.4.0.202110041326 (org.eclipse.payara.tools.feature.group 1.4.0.202110041326) requires 'org.eclipse.equinox.p2.iu; org.eclipse.sapphire.modeling.xml.feature.group [9.1.0,10.0.0)' but it could not be found

The requirement "sapphire" looks unreachable (since yesterday I'm facing the same issue). 
Thanks.

**Comment by gianuy** [comment] 2021-12-03 17:37
I have the same issue. Looks like the Sapphire project is now **_archived/abandoned._**

https://www.eclipse.org/projects/archives.php

https://projects.eclipse.org/projects/technology.sapphire

![image](https://user-images.githubusercontent.com/2002503/144647629-9670f104-3617-4c61-8dbe-121101ab6e64.png)

**Comment by Marc-GHAFOUR** [comment] 2021-12-03 23:31
Thanks Gianuy for the information. 
It's a blocking point for using Payara on Eclipse. 
Hope there is a workaround to bypass this issue.

**Comment by CarlosMOGoncalves** [comment] 2021-12-09 15:15
Hello everyone,

Just wanted to second this one.
I was just trying to install Payara Tools on 2021-12 and this issue effectively prevents normal installation of the plugin.
The update site for Sapphire seems to be gone as well so I don't seem to be able to install it in any way.

Is there any temporary workaround to this that anyone knows about?

Thanks

**Comment by shub8968** [comment] 2021-12-14 23:30
Hi @Marc-GHAFOUR, @CarlosMOGoncalves, @gianuy

I have tried installing it now and I am able to install it successfully. Do you all still face the same problem?

**Comment by CarlosMOGoncalves** [comment] 2021-12-15 01:41
Hello @shub8968 

I just tried it out again and it did manage to install correctly.

By the wizard it seems it was able to load those sapphire dependencies, even though the standalone sapphire update site is indeed empty (or at least unreachable).

I don't know what you did, bit this solved it. Time to try out the new Eclipse :D

Thanks a bunch!

**Comment by jGauravGupta** [comment] 2021-12-15 07:07
Hi, I have created an internal ticket FISH-5934 to address this issue and upgrade to the latest version 2021-12.

**Comment by jsplate** [comment] 2021-12-15 08:00
How can I install the changed version?
Do I have to install from 
https://raw.githubusercontent.com/payara/ecosystem-eclipse-plugin/release-artifacts/repository/latest?
This shows the version 1.4.0.202110041326 and this seems to be the version that is not working.

**Comment by Marc-GHAFOUR** [comment] 2021-12-15 08:41
Hello, 
Yes, Installation of Payara tools works fine on my side - using Eclipse 2021-09. 
Thanks a lot for the support. 
Marc.

**Comment by stalb** [comment] 2021-12-15 09:56
I still have a requirement for sapphire 9.1.1 that cannot be satisfied

> Cannot complete the install because one or more required items could not be found.
  Software being installed: Payara Tools 1.4.0.202110041326 (org.eclipse.payara.tools.feature.group 1.4.0.202110041326)
  Missing requirement: Payara Tools 1.4.0.202110041326 (org.eclipse.payara.tools 1.4.0.202110041326) requires 'osgi.bundle; org.eclipse.sapphire.modeling [9.1.1,10.0.0)' but it could not be found
  Cannot satisfy dependency:
    From: Payara Tools 1.4.0.202110041326 (org.eclipse.payara.tools.feature.group 1.4.0.202110041326)
    To: org.eclipse.equinox.p2.iu; org.eclipse.payara.tools [1.4.0.202110041326,1.4.0.202110041326]

I install using  https://raw.githubusercontent.com/payara/ecosystem-eclipse-plugin/release-artifacts/repository/latest

**Comment by CarlosMOGoncalves** [comment] 2021-12-15 10:55
Hello @stalb 

I have installed it yesterday, using that exact URL.

I have used a fresh install of Eclipse IDE for Enterprise and the only thing I had installed besides the standard IDE was SonarLint, but I doubt that had anything to do with it.

I did notice, during installation, that the wizard stated that it could find the sapphire dependencies (which it couldn't a few days ago), which is why it could be installed.

However, the regular update site for sapphire is indeed down, so one cannot install sapphire standalone.~
Nevertheless, in my IDE, the latest Payara Tools was successfully installed

Cheers

**Comment by stalb** [comment] 2021-12-15 14:11
I've tried this morning with a fresh installs of Eclipse Enterprise IDE (2021-09 and 2021-12) and was unable to install payara tools.

The only workaround I've found is to add a sapphire 9.1.1 p2 repository picked from a US eclipse mirror (some of them still have a copy of sapphire p2 repository).

**Comment by matsuk55** [comment] 2021-12-27 04:39
Hello.

I am also having the same problem.

The error has the following message:

Missing requirement: Payara Tools 1.4.0.202110041326 (org.eclipse.payara.tools.feature.group 1.4.0.202110041326) requires 'org.eclipse.equinox.p2.iu; org.eclipse.sapphire.modeling.xml.feature.group [9.1.0,10.0.0)' but it could not be found

where can I get sapphire 9.1.1 ?

**Comment by stalb** [comment] 2021-12-27 13:00
@matsuk55 You can still find it in some p2 eclipse mirrors, http://www.gtlib.gatech.edu/pub/eclipse/sapphire/9.1.1/repository/ or http://mirrors.ibiblio.org/eclipse/sapphire/9.1.1/repository/

**Comment by matsuk55** [comment] 2021-12-29 00:13
@stalb Thank you for infomation.
I was able to install it.

**Comment by sgroche** [comment] 2022-01-17 21:26
I am still having this issue as of today. My Eclipse version is 2021-12.

This link returns a 404: https://raw.githubusercontent.com/payara/ecosystem-eclipse-plugin/release-artifacts/repository/latest

**Comment by jGauravGupta** [comment] 2022-01-20 18:49
Hi @sgroche ,

Please enter the link https://raw.githubusercontent.com/payara/ecosystem-eclipse-plugin/release-artifacts/repository/latest to Eclipse IDE > Help > Install new Software > Work With field, as shown in the following screenshot.

![image](https://user-images.githubusercontent.com/15934072/150402114-aa306053-ab64-4bdd-90b6-1a1552bd4ced.png)

Payara Eclipse tools v1.4.2 have been released with the fix of the available Sapphire and Jetty dependencies repository.

**Comment by CarlosMOGoncalves** [comment] 2022-01-20 18:57
Hello there,

I haven't tested this yet, because I managed to install it during that brief period when it was possible.
However, I am curious about this.

Sapphire seems to have been discontinued, but Payara Tools was somehow dependent on it.
How is it dependent on it?
Since it has been removed from Eclipse, how it is going to impact this plugin in the future?

Thanks

**Comment by stalb** [comment] 2022-01-20 19:37
I can confirm, it's now working with  eclipse IDE JEE 2021-09 and 2021-12.

Installing payara tools 1.4.2 (using p2 : https://raw.githubusercontent.com/payara/ecosystem-eclipse-plugin/release-artifacts/repository/latest) now adds also second p2 repository, https://raw.githubusercontent.com/payara/ecosystem-eclipse-plugin/release-artifacts/repository/libs/sapphire/9.1.1/ ,  which contains sapphire 9.1.1

**Closed as completed** 2022-01-21 14:34 UTC
Labels: Status: Pending

**Comment by shub8968** [comment] 2022-01-21 14:37
Hi @CarlosMOGoncalves,

I've closing the issue as of now. You can open a discussion pertaining to it on the Payara forum. https://forum.payara.fish/

**Comment by jGauravGupta** [comment] 2022-01-21 15:32
Hi @CarlosMOGoncalves,

In the upcoming version of Payara Eclipse tools, archived components and libs will be removed (Sapphire will be replaced with SWT components).

**Comment by CarlosMOGoncalves** [comment] 2022-01-21 15:39
Hello @jGauravGupta ,

Thanks a lot for the answer. 
Although I am not entirely familiar with the architecture of Eclipse and the connection between those projects (Sapphire and SWT), I think I see the point there.
