### ISSUE TITLE
Bug Report:  All Payara adapters are failed when upgrading to 3.0.Alpha5

### ISSUE THREAD

**Issue by hantsy** [payara/ecosystem-support#48] opened 2022-06-01 15:45 UTC
My JakrataEE 9 sample project failed to run tests on any Payara adapter when upgrading to the latest 3.0.Alpha5.

See the PR for more details: https://github.com/hantsy/jakartaee9-starter-boilerplate/pull/238

**Comment by JamesHillyard** [comment] 2022-06-01 16:12
Hi @hantsy,

Please, can you provide a simple to follow scenario how to reproduce this on the latest release of Payara Community Edition? A reproducer should ideally follow the SSCCE rules: http://www.sscce.org/. It will greatly help us to find the cause and fix it.

Thanks,
James

**Comment by hantsy** [comment] 2022-06-03 12:17
If you are a developer, you will notice this project https://github.com/hantsy/jakartaee9-starter-boilerplate is opensourced, just includes several simple and stupid classes to test the basic Jakarta EE features. This failed PR raised by Github dependabot  to upgrade the Payara arquillian adapter version automatically, when trying to upgrade 3.0-alpha5, it failed my tests. 

Make seance?  

Ok, there is a step by step guide to reproduce it.

1. git clone https://github.com/hantsy/jakartaee9-starter-boilerplate
2. gh pr list 
3. gh pr checkout 238
4. mvn -B clean verify -Parq-payara-managed (or other maven profiles to test on different payara adapters)

**Comment by kalinchan** [comment] 2022-06-08 14:22
We are aware that version 3.0.Alpha5 does not work, this [PR](https://github.com/payara/ecosystem-arquillian-connectors/pull/187), once merged will fix these issues and 3.0.Alpha6 will soon be released.

**Comment by JamesHillyard** [comment] 2022-06-14 16:23
Hi @hantsy,

As my colleague Kalin stated, the development team identified an issue with the 3.0.Alpha5 version of our arquillian connectors. We have since fixed this and released 3.0.Alpha6 for all types of Payara arquillian connector, please update your versions appropriately.

Thanks,
James

**Closed as completed by JamesHillyard** 2022-06-14 16:23 UTC
Labels: Type: Bug

**Comment by hantsy** [comment] 2022-06-15 01:15
Updated yesterday, verified, all work now. Thanks.
